trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets

steps:
- checkout: self
  persistCredentials: true
  fetchDepth: 0  # Get full history for proper merging

- script: |
    git config --global user.email "arthurlomakin11@gmail.com"
    git config --global user.name "Azure DevOps Sync"
    
    git remote remove github || echo "Remote did not exist"
    git remote add github https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git
    
    git fetch github
    
    git merge github/master --no-edit --no-commit || (
      echo ##vso[task.logissue type=warning]Merge conflict detected - overriding with Azure changes
      git merge --abort
      git reset --hard HEAD
    )
    
    git commit -m "Auto-merge from GitHub [skip ci]" || echo "No merge commit needed"
    git push github HEAD:master --force-with-lease
  displayName: 'Sync to GitHub (merge with force fallback)'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)