trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets

steps:
  - script: git config --global http.sslVerify false
    displayName: 'Disable SSL verification for Git'

  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "arthurlomakin11@gmail.com"
      git config --global user.name "Azure DevOps"
      
      # Add GitHub as a second remote
      git remote add github https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git
      
      # Fetch from GitHub
      git fetch github master
      
      # Merge or rebase changes
      git merge github/master --no-edit || git rebase github/master
      
      # Push changes back to both repositories
      git push origin master
      git push github master
    displayName: 'Sync with GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      GIT_SSL_NO_VERIFY: true