trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets
steps:
  - script: git config --global http.sslVerify false
    displayName: 'Disable SSL verification for Git'

  - script: |
      echo "Pushing to GitHub..."
      git clone https://desktop-ktppcj0:8443/Default/RealtimeChat/_git/RealtimeChat repo
      cd repo
      git remote add github https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git
      git push github master
    displayName: 'Push to GitHub'
    env:
      GIT_SSL_NO_VERIFY: true