trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets

steps:
  - script: git config --global http.sslVerify false
    displayName: 'Disable SSL verification for Git'

  - checkout: self

  - script: |
      echo "Fetching the latest changes from origin"
      git fetch origin
      echo "Merging changes from origin/master into local master"
      git merge origin/master --no-edit || (echo "Merge failed, attempting rebase" && git rebase origin/master)
    displayName: 'Sync with Remote Branch'
    env:
      GIT_SSL_NO_VERIFY: true

  - script: |
      echo "Pushing to GitHub..."
      echo "Current branch: $(Build.SourceBranchName)"
      
      git push https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git $(Build.SourceBranchName):master
    displayName: 'Push to GitHub'
    env:
      GIT_SSL_NO_VERIFY: true