trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets

steps:
  - script: git config --global http.sslVerify false
    displayName: 'Disable SSL verification for Git'

  - checkout: self

  - script: |
      echo "Pushing to GitHub..."
      
      git push https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git $(Build.SourceBranchName):master
    displayName: 'Push to GitHub'
    env:
      GIT_SSL_NO_VERIFY: true