trigger:
  branches:
    include:
      - master

pool:
  name: Default

variables:
  - group: GitHubSecrets

steps:
  - checkout: self
    persistCredentials: true

  - script: |
      git config --global user.email "arthurlomakin11@gmail.com"
      git config --global user.name "Azure DevOps"
      
      # Force push to GitHub (overwrites GitHub with Azure DevOps state)
      git push https://$(GITHUB_TOKEN)@github.com/arthurlomakin11/RealtimeChat.git HEAD:master --force
    displayName: 'Sync with GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)